"""Request/response Pydantic models for the webhooks API.

Split from a single ``schemas.py`` god-module into a package grouped by router
(audit #408); this facade re-exports every model so
``from prefrontal.webhooks.schemas import X`` keeps working unchanged.
"""
from __future__ import annotations

from prefrontal.webhooks.schemas.admin import (
    HouseholdCreate,
    HouseholdMember,
    UserCreate,
    UserEmail,
)
from prefrontal.webhooks.schemas.anchor import (
    OutingDomain,
    OutingReturn,
    OutingStart,
    OutingStarted,
)
from prefrontal.webhooks.schemas.assistant import (
    AssistantApply,
    AssistantMessage,
)
from prefrontal.webhooks.schemas.clarify import (
    ClarificationLocalization,
    ClarificationResolve,
)
from prefrontal.webhooks.schemas.focus import (
    FocusEnd,
    FocusLog,
    FocusStart,
    FocusStarted,
)
from prefrontal.webhooks.schemas.household import (
    AgreementSet,
    AppointmentCreate,
    BalanceConfig,
    CheckinConfig,
    ChildCreate,
    ChildRename,
    ChoreDone,
    ChoreEnabled,
    ChoreSet,
    DigestConfig,
    FactClear,
    FactSet,
    InviteCreate,
    InviteRedeem,
    PetCreate,
    PetRename,
    PromptConfig,
    RoutineEnabled,
    RoutineSet,
    ShoppingAdd,
    ShoppingGot,
    StarAward,
    TierConfig,
)
from prefrontal.webhooks.schemas.impulsivity import (
    CaptureImpulse,
    ImpulseCaptured,
    SwitchImpulse,
    SwitchPause,
    SwitchResolve,
    SwitchResolved,
)
from prefrontal.webhooks.schemas.ingestion import (
    EpisodeCreated,
    HomeSet,
    LocationPing,
    MailSync,
    ShortcutPayload,
    TriageForget,
    TriageIn,
    TripDomain,
    TripLabel,
    TripReflect,
    TripRetro,
)
from prefrontal.webhooks.schemas.projects import (
    EntityProjectUpdate,
    ProjectCreate,
    ProjectReorder,
    ProjectUpdate,
)
from prefrontal.webhooks.schemas.schedule import (
    CalendarEvent,
    CalendarSync,
    CommitmentCreate,
    CommitmentDomain,
    CommitmentHardness,
    CommitmentHidden,
    CommitmentKind,
    CommitmentNotes,
    CommitmentOutcome,
    CommitmentPrepared,
    ConflictDismiss,
    PlaceCreate,
)
from prefrontal.webhooks.schemas.sensor import (
    ConversationTurn,
    ObserveRequest,
)
from prefrontal.webhooks.schemas.system import (
    SelfCareCheckConfig,
    SelfCareConfig,
    SelfCareMark,
    SmtpConfig,
)
from prefrontal.webhooks.schemas.todos import (
    AutoDecomposeConfig,
    DelegateTodo,
    DismissDecomposition,
    StepDone,
    TodoCategoryUpdate,
    TodoCreate,
    TodoDeadlineUpdate,
    TodoDomainUpdate,
    TodoNotesUpdate,
    TodoSchedule,
    TodoWindowUpdate,
)

__all__ = [
    "AgreementSet",
    "AppointmentCreate",
    "AssistantApply",
    "AssistantMessage",
    "AutoDecomposeConfig",
    "BalanceConfig",
    "CalendarEvent",
    "CalendarSync",
    "CaptureImpulse",
    "CheckinConfig",
    "ChildCreate",
    "ChildRename",
    "ChoreDone",
    "ChoreEnabled",
    "ChoreSet",
    "ClarificationLocalization",
    "ClarificationResolve",
    "CommitmentCreate",
    "CommitmentDomain",
    "CommitmentHardness",
    "CommitmentHidden",
    "CommitmentKind",
    "CommitmentNotes",
    "CommitmentOutcome",
    "CommitmentPrepared",
    "ConflictDismiss",
    "ConversationTurn",
    "DelegateTodo",
    "DigestConfig",
    "DismissDecomposition",
    "EntityProjectUpdate",
    "EpisodeCreated",
    "FactClear",
    "FactSet",
    "FocusEnd",
    "FocusLog",
    "FocusStart",
    "FocusStarted",
    "HomeSet",
    "HouseholdCreate",
    "HouseholdMember",
    "ImpulseCaptured",
    "InviteCreate",
    "InviteRedeem",
    "LocationPing",
    "MailSync",
    "ObserveRequest",
    "OutingDomain",
    "OutingReturn",
    "OutingStart",
    "OutingStarted",
    "PetCreate",
    "PetRename",
    "PlaceCreate",
    "ProjectCreate",
    "ProjectReorder",
    "ProjectUpdate",
    "PromptConfig",
    "RoutineEnabled",
    "RoutineSet",
    "SelfCareCheckConfig",
    "SelfCareConfig",
    "SelfCareMark",
    "ShoppingAdd",
    "ShoppingGot",
    "ShortcutPayload",
    "SmtpConfig",
    "StarAward",
    "StepDone",
    "SwitchImpulse",
    "SwitchPause",
    "SwitchResolve",
    "SwitchResolved",
    "TierConfig",
    "TodoCategoryUpdate",
    "TodoCreate",
    "TodoDeadlineUpdate",
    "TodoDomainUpdate",
    "TodoNotesUpdate",
    "TodoSchedule",
    "TodoWindowUpdate",
    "TriageForget",
    "TriageIn",
    "TripDomain",
    "TripLabel",
    "TripReflect",
    "TripRetro",
    "UserCreate",
    "UserEmail",
]
